server:
  port: 9099

wx:
  # ??ak?????
  ak: "xxxxx"
  # ??api
  txKey: "xxxx"
  appId: "xxx"
  secret: "xxxx"
  # ??id
  templateId: "xxxx"
  # ?????????
  love: "2020-10-13"
  # ????????
  isGregorian: true
  # ???????????
  birthdayPrincess: "1999-01-27"
  # ???????????
  birthdayMan: "1999-08-14"